language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - pypy3

install:
    - make setup

script:
    - make test

deploy:
    provider: pypi
    username: "__token__"
    password: $PYPI_TOKEN
    on:
        tags: true
